name: eleven_labs
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  cupertino_icons:
  loading_animation_widget:
  dio: ^5.3.2
  audiofileplayer: ^2.1.1
  audio_waveforms:
  grouped_list:
  uuid:
  path_provider:
  flutter_sequence_animation:

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_gen_runner:
  json_serializable:
  json_annotation:
  flutter_launcher_icons:

flutter_gen:
  output: lib/ui/common

flutter_icons:
  ios: true
  image_path: "assets/icons/el.png"

flutter:
  uses-material-design: true

  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 100
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 500
      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 800
  - family: Hyperlegible
    fonts:
      - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
        weight: 100
      - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
        weight: 800

